import Head from 'next/head'
import { Inter } from 'next/font/google'
import {getSession} from "next-auth/react";

const inter = Inter({ subsets: ['latin'] })
const { stringify } = JSON
export async function getServerSideProps(context) {
    const session = await getSession(context);
    return { props: { user: session?.user ?? null } };
}

function Home({user}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
          <pre>{user ? stringify(user, null, 2): 'no user'}</pre>
      </main>
    </>
  )
}
export default Home